env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - airbnb-base
plugins:
  - jest
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "no-underscore-dangle": "off",
  "comma-dangle": ["error", "never"],
  "jest/no-disabled-tests": "warn",
  "jest/no-focused-tests": "error",
  "jest/no-identical-title": "error",
  "jest/prefer-to-have-length": "warn",
  "jest/valid-expect": "error"
}
